// AUTOGENERATED FILE: easyjson marshaller/unmarshallers.

package easy

import (
	json "encoding/json"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

var _ = json.RawMessage{} // suppress unused package warning

func easyjson_decode_github_com_FZambia_easyerror_easy_Sample(in *jlexer.Lexer, out *Sample) {
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "data":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Data).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
}
func easyjson_encode_github_com_FZambia_easyerror_easy_Sample(out *jwriter.Writer, in *Sample) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"data\":")
	out.Raw((in.Data).MarshalJSON())
	out.RawByte('}')
}
func (v *Sample) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson_encode_github_com_FZambia_easyerror_easy_Sample(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}
func (v *Sample) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson_encode_github_com_FZambia_easyerror_easy_Sample(w, v)
}
func (v *Sample) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson_decode_github_com_FZambia_easyerror_easy_Sample(&r, v)
	return r.Error()
}
func (v *Sample) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson_decode_github_com_FZambia_easyerror_easy_Sample(l, v)
}
